/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ase_project;
import java.sql.*;

import javax.swing.JOptionPane;
/**
 *
 * @author Mahmoud
 */
public class Update_Delete_Form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Update_Delete_Form.class.getName());
    private final String Url = "jdbc:sqlserver://localhost:1433;databaseName=Hotel;user=sa;password=sa123456;encrypt=true;trustServerCertificate=true;";
    /**
     * Creates new form Deletion_Form
     */
    public Update_Delete_Form() {
        initComponents();
        LoadGuestsIDs();
        LoadAvailableRooms();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        cbGuestsID = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfFullName = new javax.swing.JTextField();
        tfDateOfBirth = new javax.swing.JTextField();
        tfNaionality = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        lUsername2 = new javax.swing.JLabel();
        lPassword3 = new javax.swing.JLabel();
        lPassword4 = new javax.swing.JLabel();
        lPassword5 = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        lPassword6 = new javax.swing.JLabel();
        tfPassportID = new javax.swing.JTextField();
        lPassword8 = new javax.swing.JLabel();
        cbRoom = new javax.swing.JComboBox<>();
        lPassword7 = new javax.swing.JLabel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        ftfGuestID = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Deletion Information"));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Multiple Guests"));
        jPanel3.setPreferredSize(new java.awt.Dimension(488, 100));

        jLabel2.setText("Guest ID");

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        cbGuestsID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(cbGuestsID, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnDelete)
                    .addComponent(cbGuestsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Update Information"));

        jLabel3.setText("Guest ID");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        lUsername2.setText("FullName");

        lPassword3.setText("Date Of Birth");

        lPassword4.setText("Nationality");

        lPassword5.setText("Phone");

        lPassword6.setText("Passport ID");

        lPassword8.setText("Room");

        cbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lPassword7.setText("Gender");

        rbMale.setText("Male");

        rbFemale.setText("Female");

        ftfGuestID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lUsername2)
                            .addComponent(jLabel3))
                        .addGap(88, 88, 88)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFullName)
                            .addComponent(ftfGuestID)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lPassword3)
                            .addComponent(lPassword4)
                            .addComponent(lPassword5)
                            .addComponent(lPassword6)
                            .addComponent(lPassword8)
                            .addComponent(lPassword7))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbMale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbFemale, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbRoom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPassportID)
                            .addComponent(tfNaionality, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfDateOfBirth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfPhone, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftfGuestID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lUsername2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPassword3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNaionality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPassword4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lPassword5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword6)
                    .addComponent(tfPassportID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword8)
                    .addComponent(cbRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lPassword7)
                    .addComponent(rbMale)
                    .addComponent(rbFemale)
                    .addComponent(btnUpdate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeRoomStatus(int Guest_ID,int status)
    {   
        Connection con =  null;
        Statement stmt =  null;
        
        try{
            con= DriverManager.getConnection(Url);
            String query = "update Rooms set Status = "+status+" where Room_ID = (select Room_ID from Guests where Guest_ID = "+Guest_ID+")";
            stmt = con.createStatement();
            
            int affectedRows = stmt.executeUpdate(query);

            if (affectedRows == 1){
                LoadGuestsIDs();
                JOptionPane.showMessageDialog(this, "Successful Registration!!!");
            }
            else
                JOptionPane.showMessageDialog(this, "Error !!!");
                    
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            if(con != null) { try{ con.close();} catch (Exception ex) {}}
            if(stmt != null) { try{ stmt.close();} catch (Exception ex) {}}
        }
    }
    
    private void LoadAvailableRooms()
    {
        cbRoom.removeAllItems();
        
        Connection con =  null;
        Statement stmt =  null;
        ResultSet result =  null;
        
        try{
            con= DriverManager.getConnection(Url);
            String query = "select Room_ID from Rooms where Status = 0";
            stmt = con.createStatement();
            result = stmt.executeQuery(query);
                    
            while(result.next())
            {
                cbRoom.addItem("Room "+result.getString("Room_ID"));   
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            if(con != null) { try{ con.close();} catch (Exception ex) {}}
            if(stmt != null) { try{ stmt.close();} catch (Exception ex) {}}
            if(result != null) { try{ result.close();} catch (Exception ex) {}}
        }
    }
    
    private void LoadGuestsIDs()
    {
        cbGuestsID.removeAllItems();
        
        
        
        
        Connection con =  null;
        Statement stmt =  null;
        ResultSet result =  null;
        try{
            con= DriverManager.getConnection(Url);
            String query = "select Guest_ID from Guests";
            stmt = con.createStatement();
            result = stmt.executeQuery(query);
                    
            while(result.next())
            {
                cbGuestsID.addItem(result.getString("Guest_ID"));   
            }
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            if(con != null) { try{ con.close();} catch (Exception ex) {}}
            if(stmt != null) { try{ stmt.close();} catch (Exception ex) {}}
            if(result != null) { try{ result.close();} catch (Exception ex) {}}
        }
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
        
        Connection con =  null;
        Statement stmt =  null;
        
        try{

            con= DriverManager.getConnection(Url);
            stmt = con.createStatement();
            int guest_id = Integer.parseInt(cbGuestsID.getSelectedItem().toString());
            String query = "delete from Guests where Guest_ID = "+guest_id+"";    
            ChangeRoomStatus(guest_id,0);
            int affectedRows = stmt.executeUpdate(query);

            if (affectedRows == 1){
                LoadGuestsIDs();
                LoadAvailableRooms();
                JOptionPane.showMessageDialog(this, "Successful Registration!!!");
            }
            else{
                JOptionPane.showMessageDialog(this, "Error !!!");
                ChangeRoomStatus(guest_id,1);
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            if(con != null) { try{ con.close();} catch (Exception ex) {}}
            if(stmt != null) { try{ stmt.close();} catch (Exception ex) {}}
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int Guest_ID = Integer.parseInt(ftfGuestID.getText());
        String FullName = tfFullName.getText();
        String DateOfBirth = tfDateOfBirth.getText();
        String Nationality = tfNaionality.getText();
        String Passport_ID = tfPassportID.getText();
        String Phone = tfPhone.getText();
        int Gender = (rbMale.isSelected()) ? 1 : 0; 
        
        if(ftfGuestID.getText().isEmpty())
            JOptionPane.showMessageDialog(this, "Please enter your id");
        
        if (FullName.isEmpty())
            JOptionPane.showMessageDialog(this, "Please enter your full name");

        if (DateOfBirth.isEmpty())
            JOptionPane.showMessageDialog(this, "Please enter your date of birth");

        if (Nationality.isEmpty())
            JOptionPane.showMessageDialog(this, "Please enter your nationality");

        if (Phone.isEmpty())
            JOptionPane.showMessageDialog(this, "Please enter your phone");

        if (Passport_ID.isEmpty())
            JOptionPane.showMessageDialog(this, "Please enter your passport ID");
        
        if (!(rbMale.isSelected() || rbFemale.isSelected()))
            JOptionPane.showMessageDialog(this, "Please select your gender");
        
        Connection con =  null;
        Statement stmt =  null;
        
        if (ftfGuestID.getText().isEmpty() || FullName.isEmpty() || DateOfBirth.isEmpty() || Nationality.isEmpty() || Phone.isEmpty()
            || Passport_ID.isEmpty() || (!(rbMale.isSelected() || rbFemale.isSelected())))
                return;
        
        try{

            con= DriverManager.getConnection(Url);
            stmt = con.createStatement();
            int Room_ID = Integer.parseInt(cbRoom.getSelectedItem().toString());
            String query = "update Guests" +
                            "set FullName = '"+FullName+"'," +
                            "DateOfBirth= '"+DateOfBirth+"'," +
                            "Nationality = '"+Nationality+"'," +
                            "Phone = '"+Phone+"'," +
                            "Passport_ID = "+Passport_ID+"," +
                            "Gender = "+Gender+"," +
                            "Room_ID = "+Room_ID+"" +
                            "where Guest_ID = "+Guest_ID+" ";    
            int affectedRows = stmt.executeUpdate(query);
            ChangeRoomStatus(Guest_ID,0);
            
            if (affectedRows == 1){
                LoadAvailableRooms();
                JOptionPane.showMessageDialog(this, "Successful Registration!!!");
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Error !!!");
                
            }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            ChangeRoomStatus(Guest_ID,1);
            if(con != null) { try{ con.close();} catch (Exception ex) {}}
            if(stmt != null) { try{ stmt.close();} catch (Exception ex) {}}
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Update_Delete_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbGuestsID;
    private javax.swing.JComboBox<String> cbRoom;
    private javax.swing.JFormattedTextField ftfGuestID;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lPassword3;
    private javax.swing.JLabel lPassword4;
    private javax.swing.JLabel lPassword5;
    private javax.swing.JLabel lPassword6;
    private javax.swing.JLabel lPassword7;
    private javax.swing.JLabel lPassword8;
    private javax.swing.JLabel lUsername2;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField tfDateOfBirth;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JTextField tfNaionality;
    private javax.swing.JTextField tfPassportID;
    private javax.swing.JTextField tfPhone;
    // End of variables declaration//GEN-END:variables
}
